language: php

php:
  - 7.1.3
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  # - ./vendor/bin/phpcs src
  - ./vendor/bin/phpmd src text phpmd.xml
  - ./vendor/bin/phpstan analyse src
